"""
A utility to process Rigol oscilloscope wfm files.

For full documentation see <https://RigolWFM.readthedocs.io>

Example::

    >>> import matplotlib.pyplot as plt
    >>> from RigolWFM import Wfm

    >>> filename = 'example.wfm'
    >>> w = Wfm.from_file(filename)
    >>> w.plot()
    >>> plt.show()

Info waveform class::

    >>> from RigolWFM import Wfm
    >>> help(Wfm)

Info about channel class::

    >>> from RigolWFM import Channel
    >>> help(Channel)

All the parsing code is auto-generated by `kaitai-struct-compiler`
based on `.ksy` files that describe the binary format of the Rigol
oscilloscope `.wfm` files.
"""

from .channel import Channel
from .wfm import Wfm, detect_model

__version__: str = "1.0.0"
__author__: str = "Scott Prahl"
__email__: str = "scott.prahl@oit.edu"
__copyright__: str = "2020-26, Scott Prahl"
__license__: str = "BSD 3-clause"
__url__: str = "https://github.com/scottprahl/RigolWFM"

__all__ = [
    "Wfm",
    "Channel",
    "detect_model",
    "__version__",
    "__author__",
    "__email__",
    "__copyright__",
    "__license__",
    "__url__",
]
