"""
A utility to process Rigol oscilloscope wfm files.

For full documentation see <https://RigolWFM.readthedocs.io>

Example::

    >>> import matplotlib.pyplot as plt
    >>> import RigolWFM.wfm as rigol

    >>> filename = 'example.wfm'
    >>> scope = 'DS1000E'

    >>> w = rigol.Wfm.from_file(filename, scope)
    >>> w.plot()
    >>> plt.show()

Info waveform class::

    help(rigol.wfm)

Info about channel class::

    help(rigol.channel)

All the parsing code is auto-generated by `kaitai-struct-compiler`
based on `.ksy` files that describe the binary format of the Rigol
oscilloscope `.wfm` files.
"""

__version__: str = "1.0.0"
__author__: str = "Scott Prahl"
__email__: str = "scott.prahl@oit.edu"
__copyright__: str = "2020-26, Scott Prahl"
__license__: str = "BSD 3-clause"
__url__: str = "https://github.com/scottprahl/RigolWFM.git"
