"""
Utilities for reading oscilloscope waveform files.

RigolWFM started with Rigol `.wfm` support and now includes normalized
parsers for Rigol, Tektronix, LeCroy, Agilent / Keysight, Siglent,
Yokogawa, and Rohde & Schwarz waveform exports.

For full documentation see <https://RigolWFM.readthedocs.io>

Example::

    >>> import matplotlib.pyplot as plt
    >>> from RigolWFM import Wfm
    >>> w = Wfm.from_file('example.wfm')
    >>> w.plot()
    >>> plt.show()

Info waveform class::

    >>> from RigolWFM import Wfm
    >>> help(Wfm)

Info about channel class::

    >>> from RigolWFM import Channel
    >>> help(Channel)

Scope family aliases::

    >>> from RigolWFM import DS4000_scopes
    >>> print(DS4000_scopes)

Much of the binary parsing code is auto-generated by
`kaitai-struct-compiler` from `.ksy` schemas. Handwritten adapter
modules normalize those low-level parsers into the common `Wfm` and
`Channel` interfaces.
"""

from .channel import Channel
from .wfm import (
    Wfm,
    detect_model,
    valid_scope_list,
    DS1000B_scopes,
    DS1000C_scopes,
    DS1000D_scopes,
    DS1000E_scopes,
    DS1000Z_scopes,
    DS2000_scopes,
    DS4000_scopes,
    DS5000_scopes,
    DS6000_scopes,
    DS7000_scopes,
    DS8000_scopes,
    DHO1000_scopes,
    MSO5074_scopes,
)

__version__: str = "1.5.0"
__author__: str = "Scott Prahl"
__email__: str = "scott.prahl@oit.edu"
__copyright__: str = "2020-2026, Scott Prahl"
__license__: str = "BSD 3-clause"
__url__: str = "https://github.com/scottprahl/RigolWFM"

__all__ = [
    "Wfm",
    "Channel",
    "detect_model",
    "valid_scope_list",
    "DS1000B_scopes",
    "DS1000C_scopes",
    "DS1000D_scopes",
    "DS1000E_scopes",
    "DS1000Z_scopes",
    "DS2000_scopes",
    "DS4000_scopes",
    "DS5000_scopes",
    "DS6000_scopes",
    "DS7000_scopes",
    "DS8000_scopes",
    "DHO1000_scopes",
    "MSO5074_scopes",
    "__version__",
    "__author__",
    "__email__",
    "__copyright__",
    "__license__",
    "__url__",
]
